name: 'Mirroring workflow'
on:
  push:
    branches: [ 'main' ]
env:
  MIRROR_URL: 'git@github.com:EpitechPromo2027/B-FUN-400-REN-4-1-wolfram-thibaut.hebert-henriette.git'
jobs:
  push_to_mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'main'
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ env.MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.SSH_MIRROR_KEY }}
